version: '3'
services:
  graphql:
    image: node:18.10.0-alpine
    working_dir: '/app'
    ports:
      - 4000:4000
    volumes:
      - ../../server/:/app
      - graphql-deps:/app/node_modules
    command: sh -c "npm i && npm run start"
  front:
    image: node:18.10.0-alpine
    working_dir: '/app'
    volumes:
      - ../../:/app
      - front-deps:/app/node_modules
    command: sh -c "npm i && npm run start"
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf.template
    environment:
      NODE_HOST: http://front:3000
    entrypoint: ["/entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
volumes:
  graphql-deps:
  front-deps:

